apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: machineset-configs
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    policies.kyverno.io/title: Inject Infrastructure Name
    policies.kyverno.io/category: OpenShift
    policies.kyverno.io/severity: medium
    kyverno.io/kyverno-version: 1.10.0
    policies.kyverno.io/minversion: 1.10.0
    kyverno.io/kubernetes-version: "1.26"
    policies.kyverno.io/subject: MachineSet
    policies.kyverno.io/description: >-
      A required component of a MachineSet is the infrastructure name which is a random string
      created in a separate resource. It can be tedious or impossible to know this for each
      MachineSet created. This policy fetches the value of the infrastructure name from the
      Cluster resource and replaces all instances of TEMPLATE in a MachineSet with that name.
spec:
  schemaValidation: false
  rules:
  - name: replace-template
    match:
      any:
      - resources:
          kinds:
          - machine.openshift.io/v1beta1/MachineSet
          operations:
          - CREATE
    context:
    - name: cluster
      apiCall:
        urlPath: /apis/config.openshift.io/v1/infrastructures/cluster
    - name: infraid
      variable:
        jmesPath: cluster.status.infrastructureName
    - name: machineset
      apiCall:
        urlPath: /apis/machine.openshift.io/v1beta1/namespaces/openshift-machine-api/machinesets/{{cluster}}-worker-eastus1
    - name: resourcegroup
      variable:
        jmesPath: machineset.spec.template.spec.providerSpec.value.resourceGroup
    - name: vnet
      variable:
        jmesPath: machineset.spec.template.spec.providerSpec.value.vnet
    - name: loadbalancer
      variable:
        jmesPath: machineset.spec.template.spec.providerSpec.value.publicLoadBalancer
    - name: networkgroup
      variable:
        jmesPath: machineset.spec.template.spec.providerSpec.value.networkResourceGroup
    mutate:
      patchesJson6902: |-
        - op: replace
          path: /metadata
          value: {{ replace_all(to_string(request.object.metadata),'INFRA', infraid) }}
        - op: replace
          path: /spec
          value: {{ replace_all(to_string(request.object.spec),'INFRA', infraid) }}
        - op: replace
          path: /spec.template.spec.providerSpec.value.networkResourceGroup
          value: {{ networkgroup }}
        - op: replace
          path: /spec.template.spec.providerSpec.value.vnet
          value: {{ vnet }}
        - op: replace
          path: /spec.template.spec.providerSpec.value.publicLoadBalancer
          value: {{ loadbalancer }}
        - op: replace
          path: /spec.template.spec.providerSpec.value.resourceGroup
          value: {{ resourcegroup }}