apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace/openshift-gitops-operator.yaml
- namespace/k8s-secrets.yaml
- operator/openshift-gitops-operator.yaml
- gitops/app/hello-chris.yaml
- gitops/infra/infra-helm.yaml
- gitops/infra/kyverno.yaml
- gitops/infra/pipelines.yaml
- gitops/infra/infra-secrets.yaml
- gitops/infra/azure-key.yaml.yaml
- gitops/rbac/cluster-role-gitops.yaml
- gitops/rbac/cluster-rolebinding-gitops.yaml
patches:
- target:
    kind: ClusterRoleBinding
    name: system:openshift:scc:privileged
  patch: |
    - op: add
      path: /subjects/0
      value:
        kind: ServiceAccount
        name: secrets-store-csi-driver
        namespace: k8s-secrets-store-csi`
    - op: add
      path: /subjects/1
      value:
        kind: ServiceAccount
        name: csi-secrets-store-provider-azure
        namespace: k8s-secrets-store-csi`