apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace/openshift-gitops-operator.yaml
- operator/openshift-gitops-operator.yaml
- gitops/app/hello-chris.yaml
- gitops/infra/kyverno.yaml
- gitops/infra/pipelines.yaml
- gitops/rbac/cluster-role-gitops.yaml
- gitops/rbac/cluster-rolebinding-gitops.yaml

patches:
- patch: |-
    - op: add
      path: /data/resource.customizations.health.argoproj.io_Application
      value:  -|
        hs = {}
        hs.status = "Progressing"
        hs.message = ""
        if obj.status ~= nil then
          if obj.status.health ~= nil then
            hs.status = obj.status.health.status
            if obj.status.health.message ~= nil then
              hs.message = obj.status.health.message
            end
          end
        end
        return hs    
  target:
    kind: ConfigMap
    name: argocd-cm
