---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

patches:
- patch: |-
    - op: add
      path: /metadata/annotations/secrets
      value:  "oauth-app-client-secret"
  target:
    kind: Namespace
    name: openshift-config 