---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    config.example.com/managed-by: gitops
    config.example.com/scm-url: https://github.com/cnuland/hello-chris-tekton-chains.git
  name: openshift-gitops-operator
spec: