---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-machineset
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-machine-api
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      parameters: []
    chart: aro-machinesets
    repoURL: https://rh-mobb.github.io/helm-charts/
    targetRevision: 0.1.2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true