apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-chris
  namespace: openshift-gitops-operator
spec:
  destination:
    namespace: 
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      jsonnet: {}
      recurse: true
    path: k8s
    repoURL: https://github.com/cnuland/hello-chris-tekton-chains.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - PruneLast=true