---
apiVersion: v1
kind: Namespace
metadata:
  name: hello-chris
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops
spec: