apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-chris
    app.kubernetes.io/component: hello-chris
    app.kubernetes.io/instance: hello-chris
  name: hello-chris
  namespace: hello-chris
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    deployment: hello-chris
status:
  loadBalancer: {}
