apiVersion: v1
kind: PersistentVolume
metadata:
  name: tekton-pv
  namespace: hello-chris
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
