---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tekton-pvc
  namespace: hello-chris
spec:
  storageClass: managed-premium
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

