---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    config.example.com/managed-by: gitops
    config.example.com/scm-url: https://github.com/cnuland/hello-chris-tekton-chains.git
  name: openshift-gitops-operator
  namespace: openshift-gitops-operator
spec:
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  annotations:
    config.example.com/managed-by: gitops
    config.example.com/scm-url: https://github.com/cnuland/hello-chris-tekton-chains.git
  name: openshift-gitops-operator
  namespace: openshift-gitops-operator
spec:
  channel: gitops-1.3
  installPlanApproval: Automatic
  name: openshift-gitops-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: openshift-gitops-operator.v1.3.13